import requests
r = requests.get('http://localhost:5000/predict', params={ 'age' : 1 ,'health' : 15 ,'absences' : 10})

# {'school': 0,
#                                                           'sex': 0,
#                                                           'age': 18,
#                                                           'address': 1,
#                                                           'famsize': 0,
#                                                           'Pstatus': 0,
#                                                           'Medu': 4,
#                                                           'Fedu': 4,
#                                                           'Mjob': 0,
#                                                           'Fjob': 4,
#                                                           'reason': 0,
#                                                           'guardian': 1,
#                                                           'traveltime': 2,
#                                                           'studytime': 2,
#                                                           'failures': 0,
#                                                           'schoolsup': 1,
#                                                           'famsup': 0,
#                                                           'paid': 0,
#                                                           'activities': 0,
#                                                           'nursery': 1,
#                                                           'higher': 1,
#                                                           'internet': 0,
#                                                           'romantic': 0,
#                                                           'famrel': 4,
#                                                           'freetime': 3,
#                                                           'goout': 4,
#                                                           'Dalc': 1,
#                                                           'Walc': 1,
#                                                           'health': 3,
#                                                           'absences': 6})
print(r.content)
